---
collections:
  - name: community.general
    version: 5.1.0
  - name: community.sops
    version: 1.2.2
  - name: ansible.posix
    version: 1.5.4
  - name: ansible.utils
    version: 2.6.1
roles:
  - src: xanmanning.k3s
    version: v3.1.2
  - src: https://github.com/geerlingguy/ansible-role-nfs
    name: geerlingguy.nfs
    version: 2.0.0
