apiVersion: v1
kind: Secret
metadata:
  name: harbor-simplebookmarks-helm-repository
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: harbor-simplebookmarks-helm-repository
  url: harbor.${SECRET_DOMAIN}
  type: helm
  username: ${SECRET_SIMPLEBOOKMARKS_DOCKER_USERNAME}
  password: ${SECRET_SIMPLEBOOKMARKS_DOCKER_PASSWORD}
  enableOCI: "true"
