apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certificate.yaml
  - ingress.yaml
  - install.yaml
  - simplebookmarks-git-repo.sops.yaml
  - simplebookmarks-helm-repo.sops.yaml
patchesStrategicMerge:
  - argocd-cmd-params-cm.yaml
namespace: argocd
