apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: elastic
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/elastic/helm-charts
  ref:
    tag: v8.5.1
