---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: github-actions-runner-controller
  namespace: default
spec:
  type: "oci"
  interval: 5m0s
  url: oci://ghcr.io/actions/actions-runner-controller-charts
