apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: harbor
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/goharbor/harbor-helm
  ref:
    tag: v1.15.1
