apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - default-pool
  nodeSelectors:
  - matchLabels:
      node-role.kubernetes.io/master: "true"
  interfaces:
    - eth0
