apiVersion: v1
data:
    encryptionkey: ENC[AES256_GCM,data:N4JQcBUYllzZmI1N7S894HMmLDE1zwjovOcyjLlkFII/Np2cX2rEl1eyTvhUBNLWkPO7AJODt5hXYZ3OmSZ2GVrUJ8s=,iv:/ubTecG1qqUVjx64cuKOQ4+qP0gvbBxwz8GwyS7C15o=,tag:trA3ah6j5ebksev3yVLPUg==,type:str]
kind: Secret
metadata:
    name: kibana-encryption-key-secret
    namespace: elasticsearch
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1adgzd3kcelpz23rfek7hgp9saega7vea9n2fpkd6qqunpczfpv5sw8ns4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGeTZSNzgwaEVJWnpnQzJF
            MXNZcDM4bGxsVnhFQmVlTTN0RkRGbk43Ulg4CnE0L3d2MUNwOFhFSXBleWpubmZR
            dW5XU3RjTE9lU0paeG4vaEg4UXhGbW8KLS0tIGJoNWpPaUNBTk9kbmlpLzA0MGFr
            Zmc4VjUzSVN2ZGVERzJRM1VwRlZBMVUK342ovyr4vP73aThBsPKUEqPe7Q1ULf3l
            vT5NeQcGoStxRn7QHHNDlrfy9lXNiWhrONMCl4FJMeqAbA0jbNpO6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-25T17:16:46Z"
    mac: ENC[AES256_GCM,data:TVKJQPDZJsQ23TpYxRE36GYrYJy37nHgI2O1G6/KxxTNO1KBrFbZaqxVrPcd5HhM/ja2Fh18UVKS+dzbLx4UqbrRYDIVLyBZtpQv4J1kR66naqJbakLjRIpA5ndeuUu/3y+c8OifXptX9gWk9s4HLFjUiwn76FkvaG/rkd2D/Vc=,iv:4dFBqRI5Yp/9Tys2mOpegLuat2zdCl9rHWnEJ80cV8E=,tag:ZW9YpD6Wtzcb5/iXJIK3gQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
