apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - elastic-ca-secret.sops.yaml
  - elastic-certificate-secret.sops.yaml
  - elastic-credentials-secret.sops.yaml
  - kibana-certificate-secret.sops.yaml
  - kibana-encryption-key-secret.sops.yaml
  - logstash-certificate-secret.sops.yaml
  - helm-release-elasticsearch.yaml
  - helm-release-kibana.yaml
  - helm-release-logstash.yaml
namespace: elasticsearch
