---
kubernetes:
  children:
    master:
      hosts:
        k8s-0:
          ansible_host: 78.47.255.238
    worker:
      hosts:
        k8s-1:
          ansible_host: 88.99.225.87
        k8s-2:
          ansible_host: 78.47.70.235
    nfs:
      hosts:
        nfs-1:
          ansible_host: 116.203.51.152
