---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: Etc/UTC
  METALLB_LB_RANGE: 88.198.145.218/32
  METALLB_K8S_GATEWAY_ADDR: 
  METALLB_TRAEFIK_ADDR: 88.198.145.218
