---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gha-runner-scale-set-controller
  namespace: github
spec:
  interval: 5m
  chart:
    spec:
      chart: gha-runner-scale-set-controller
      version: 0.7.0
      sourceRef:
        kind: HelmRepository
        name: github-actions-runner-controller
        namespace: flux-system

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gha-runner-scale-set
  namespace: github
spec:
  interval: 5m
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.7.0
      sourceRef:
        kind: HelmRepository
        name: github-actions-runner-controller
        namespace: flux-system
  values:
    githubConfigUrl: "${SECRET_GITHUB_ACTIONS_CONFIG_URL}"
    githubConfigSecret: github-token-secret
    maxRunners: 3
    #controllerServiceAccount:
    #  namespace: arc-system
    #  name: gha-runner-scale-set-controller-gha-rs-controller
