---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: ttrss
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: postgresql
      version: 10.16.2
      sourceRef:
        kind: HelmRepository
        name: bitnami-pre-2022
        namespace: flux-system
      interval: 5m
  values:
    global:
      storageClass: nfs-client
    pgHbaConfiguration: |-
      local all all trust
      host all all localhost trust
      host all all 10.42.0.0/16 trust
      host all all 10.43.0.0/16 trust
    ## This is for new versions
    #global:
    #  storageClass: nfs-client
    #  postgresql:
    #    auth:
    #      username: ttrss
    #      password: ttrss
    #      database: ttrss
    #primary:
    #  pgHbaConfiguration: |-
    #    local all all trust
    #    host all all localhost trust
    #    host all all 10.42.0.0/16 trust
    #    host all all 10.43.0.0/16 trust
