---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: ttrss
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: postgresql
      version: 11.9.13
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    global:
      storageClass: nfs-client
      postgresql:
        auth:
          username: ttrss
          password: ttrss
          database: ttrss
    primary:
      pgHbaConfiguration: |-
        local all all trust
        host all all localhost trust
        host all all 10.42.0.0/16 trust
        host all all 10.43.0.0/16 trust
