apiVersion: v1
kind: Service
metadata:
  name: ttrss
  namespace: ttrss
  labels:
    app: ttrss
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: ttrss

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttrss
  labels:
    app: ttrss
  namespace: ttrss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ttrss
  template:
    metadata:
      labels:
        app: ttrss
    spec:
      containers:
      - name: ttrss
        image: harbor.${SECRET_DOMAIN}/horsducommun/ttrss
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 512Mi
        env:
          - name: BASE_URL
            value: "https://rss.${SECRET_DOMAIN}"
          - name: DB_TYPE
            value: "pgsql"
          - name: DB_HOST
            value: "postgres-ttrss-postgresql"
          - name: DB_PORT
            value: "5432"
          - name: DB_NAME
            value: "ttrss"
          - name: DB_USER
            value: "ttrss"
          - name: DB_ENV_USER
            value: "postgres"
      imagePullSecrets:
        - name: docker-registry-ttrss
