---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ontrack
  namespace: ontrack
spec:
  interval: 5m
  chart:
    spec:
      chart: ontrack/ontrack
      sourceRef:
        kind: HelmRepository
        name: ontrack
        namespace: flux-system
  values:
    ontrack:
      url: "https://ontrack.${SECRET_DOMAIN}"
