apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - ontrack-casc-secret.sops.yaml
namespace: ontrack
configMapGenerator:
  - name: ontrack-casc
    files:
      - ontrack-casc.yaml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
