apiVersion: v1
kind: Secret
metadata:
    name: ontrack-casc-secret
    namespace: ontrack
stringData:
    ontrack-casc-secret.yaml: ENC[AES256_GCM,data:MbEAjhV0HPf23ppVbze4TfR37DyEr3KWhopNbvdb9UPz6ok29rDuDoE6oaaaD8geS1irW3qS5/WOolnaQHnE7gyPdqibI3Euo/KO9okoriz9EzzJnVzXo+eSI2r7F9vtAfJSkrS4aAG1iUn10vh0THHOULB9WBzKeN1lqFIHk27TjGk3IwqE2Pcf/331kaaO/yUr7Qs9zMKkjkg7ZEd5zjCeekxrf5g=,iv:90jjBN4sHC9ZGb0Pqb/K1fUhQnvvr/K5XxYDytdDLQo=,tag:jKipBCxqVQJbl3kjCtAC5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1adgzd3kcelpz23rfek7hgp9saega7vea9n2fpkd6qqunpczfpv5sw8ns4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtckxRbnpoVEsvZFR1a0pD
            Z3R1MUUrMHBsYjZGWjZDOFdIZk9ZVWpmY1RzCmJHODRwUUY1YnlvcnVKV0FRRXFS
            b3ZzclFldFVXdHFFcjY0Tm8xQmI4bzAKLS0tIDk4NEVpUVhlQUp4elV0amgvdGlq
            dG1LbmpUMkNlMGVEbHprU2hjczZ3NWsKW/e/J4LSDOKmeYaGe90tfnmVy/g0ggr6
            8wVwE3RaOoFRDCb71iRc0JT/4IXUpszKJ7pPJE0kRww10ZjKfP+XHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-17T15:49:42Z"
    mac: ENC[AES256_GCM,data:dONSjU/2wDNM1QxInWkz0mXJS678cyXdulFU7wJ4cxl1aes3Cf9xss1vq/jjHqmrK8SOXM6y1IohOU95vlYNh5uingxN9Z7nsLrBlKTsqMuE1EEqxPNJPvVE9SoaJxDCduN9bmFTmQvM7yysJGLfjOhVBHp68TUadQq3V8whoQ0=,iv:PVWzqdS0J2VdXSVJkg9/Mo9mHkNafyLll6fGD/L90eE=,tag:w1aWFxPu7g4erwUJKy7aQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
