apiVersion: v1
kind: Secret
metadata:
    name: ontrack-casc-secret
    namespace: ontrack
stringData:
    ontrack-casc-secret.yaml: ENC[AES256_GCM,data:xqPSH4QERRIHruPlA8lQh5Dvy7s5ayIl2Naupf5sbHStIZ7TwI6Ba92ehEju759R/ojOY8bHpn3usOMYG+9s1ywSDKtBlZY4PreLw5tosAvbv+MsNu40jF9sonv4ABQT3sCfMdKIqoaNtb67SWqVfpq8VaRz5SS7H+FLVnnjrPafSh1hU+bAebSjs1DMTI2C4j3+z5GmCew6yBVkfdY1fhg=,iv:RoinlGNJ8wWcDp8MxToOEwDgkuKw9z1sNhPN+nP7g+w=,tag:QhFA/FOfKOQrwvsNcGBVvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1adgzd3kcelpz23rfek7hgp9saega7vea9n2fpkd6qqunpczfpv5sw8ns4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtckxRbnpoVEsvZFR1a0pD
            Z3R1MUUrMHBsYjZGWjZDOFdIZk9ZVWpmY1RzCmJHODRwUUY1YnlvcnVKV0FRRXFS
            b3ZzclFldFVXdHFFcjY0Tm8xQmI4bzAKLS0tIDk4NEVpUVhlQUp4elV0amgvdGlq
            dG1LbmpUMkNlMGVEbHprU2hjczZ3NWsKW/e/J4LSDOKmeYaGe90tfnmVy/g0ggr6
            8wVwE3RaOoFRDCb71iRc0JT/4IXUpszKJ7pPJE0kRww10ZjKfP+XHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-17T15:58:34Z"
    mac: ENC[AES256_GCM,data:I37Zw0bCQjIhigp1qCVgk0oHMz6JIX/Ul5Q6vgvuUMpwdqT2W2iA71e5pjOPT+2DSp+IpHKkDkJCGCIhRRarzb3+RxY7yq8N1OpRElDTboJZQANByOQdT+Byy2kVGwO9Z2ZBlR/+ta0YDbPKcD2k3GYeA6eKizfntlDP1aNuNnU=,iv:N8yQC+qOUCDs8RSheawYNRhc0QfGMkXRSOHtfIgxOAs=,tag:BGblgweMvnLWDeKa2+D0sQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
