---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 5m
  chart:
    git: https://github.com/goharbor/harbor-helm
    ref: master
  values:
    expose:
      tls:
        secretName: "tls-harbor-${SECRET_DOMAIN}"
        notarySecretName: "tls-harbor-${SECRET_DOMAIN}"
      ingress:
        hosts:
          core: harbor.${SECRET_DOMAIN}
          notary: notary.${SECRET_DOMAIN}
        annotations:
          ingress.kubernetes.io/ssl-redirect: "true"
          ingress.kubernetes.io/proxy-body-size: "0"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    externalURL: https://harbor.${SECRET_DOMAIN}
    persistence:
      persistentVolumeClaim:
        storageClass: nfs-client
    harborAdminPassword: "admin"
    secretKey: ${SECRET_HARBOR_SECRET_KEY}
    chartmuseum:
      enabled: false
    notary:
      enabled: false
