apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    SECRET_ALERT_MANAGER_DISCORD_WEBHOOK: ENC[AES256_GCM,data:ZK3pv6ng9063PlsJMAOS9zFk2/z9qiIoeif/ekeuQ+9jBTOYM+M3isJteh/61LZn7ULZ0kx5d80ONaKDs2fMgIkwclWOwcKHt6VYILJmTNi4+NkYpc3KJgZChp6AiyS9nUEx/87xMoxYUAP7qL0+91gdb9QYvKSL,iv:II7MEVk25BcQ3QripdSNa51GE+pHAl98Dhc+UpyMdlk=,tag:KysswtLDDDko7FJnnDLORw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1adgzd3kcelpz23rfek7hgp9saega7vea9n2fpkd6qqunpczfpv5sw8ns4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTWVFZ3NmYUZUQVUwS3V3
            M09ybWhYOG9WMURTbngzUlV0TmsxUUFFc3lnCmF5SjB1NW52R3JZMXFHUjhPcU9L
            ZzhoSk44WUtBeHhZZ2pmSmRtOFFrMm8KLS0tIEpLbDFyVFNYc0xYT3A0c0hiUHlw
            eEV1TDZQWjBQcS9FRVpHcVRLM0ZHOTgKxVQq8Lbdg2ER43gg/l1PXzTR5iAeon+y
            o+XNCqV2NwBX9ZKbWPSysXK/5SuDJ2A24Bmmxu/qX7FZce9AC58Ciw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-30T16:47:45Z"
    mac: ENC[AES256_GCM,data:FOei+JZqaWtdusiO1cYBTP6pTQcXfIgB8z0/cAlblL8sVrByY+wIdeRic0VX6cgzulvlvG7ACnHBd/6+hIgwg2FYWdJ4pRhBzDz3DWL2mGAJzPfE3Jie3wrZJozWsqBuwXFV9f2yOS0TpxZZ99Nqe6tTwDJy7rNcnxp85NGecdc=,iv:48LnrxefvsE92oOUb63K1yzg91xZ/jTMZ6olQbvLBBk=,tag:p13tiWI/HzhUaTNkfVaD7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
