---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 30.2.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
      interval: 5m
  values:
    alertmanager:
      ingress:
        enabled: false
    grafana:
      enabled: true
      adminPassword: ${SECRET_GRAFANA_ADMIN_PASSWORD}
      ingress:
        enabled: true
        annotations:
          ingress.kubernetes.io/ssl-redirect: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - grafana.${SECRET_DOMAIN}
        path: /
        tls:
        - secretName: grafana-${SECRET_DOMAIN}
          hosts:
          - grafana.${SECRET_DOMAIN}
    kubeApiServer:
      enabled: true
    kubelet:
      enabled: true
    kubeControllerManager:
      enabled: false
    coreDns:
      enabled: true
    kubeDns:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeProxy:
      enabled: false
    kubeStateMetrics:
      enabled: true
    nodeExporter:
      enabled: true
    prometheus:
      enabled: true
      ingress:
        enabled: true
        annotations:
          ingress.kubernetes.io/ssl-redirect: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        labels: {}
        hosts:
          - prometheus.${SECRET_DOMAIN}
        paths:
        - /
        tls:
          - secretName: prometheus-.${SECRET_DOMAIN}
            hosts:
              - prometheus.${SECRET_DOMAIN}
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: nfs-client
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi
          selector: {}
