---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: nfs-provisioner-source
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner
  ref: master
  ignore: |
    # exclude all
    /*
    # include charts dir
    !/charts

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: nfs-provisioner
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/nfs-subdir-external-provisioner
      version: 4.0.14
      sourceRef:
        kind: GitRepository
        name: nfs-provisioner-source
        namespace: flux-system
  values:
    nfs:
      server: 10.0.0.100
      path: /srv/nfs
