---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: nfs-provisioner
spec:
  interval: 5m
  chart:
    git: https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner
    ref: master
  values:
    configInline:
      nfs:
        server: 10.0.0.100
        path: /srv/nfs
