apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default
  - kube-system
  - networking
  - system-upgrade
  - monitoring
  - argocd
  - harbor
  - ttrss
  # - oidc-traefik-example
  - oidc-oauth2-proxy-example
  - simplebookmarks-staging
  - simplebookmarks-production
