# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: traefik-forwarder-auth-secret
    namespace: echoserver-secure
stringData:
    PROVIDERS_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:obi4Bb1J2XQiRx3Iw7KpnENPUM+U2+lnemQLsOjW1Rj5kRsO7u4t00aCgj73smIcaNHGUDHe5C3XSH/HakUGrik5vO6w0S7H/BqklF3QZP21+Qf8G+3juQ==,iv:8ynC64R5joqAzZ8bv7LCrkf42YoyabUBQUhYzCEwP7s=,tag:yyc3PMCBoSPbRuZjcF8hYA==,type:str]
    SECRET: ENC[AES256_GCM,data:GUCsKo7tUAYPXyip425FnkK3HI4HCEo84NpUyuGhf9U+nIkci5WB8dOmiiE=,iv:CbWgn6fDRiEf/kZfW6wQhfO0V/HZQoiqhKXVKEMf8Ns=,tag:Okju4t6hQP9M1NOVmTOBKQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1adgzd3kcelpz23rfek7hgp9saega7vea9n2fpkd6qqunpczfpv5sw8ns4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWMnBZYlZMek9Kc2R3UDN1
            TWR1Y01XODBUQ2Y0NkFEKzkwVENuSUpxdTFvCjJKcVMxeE1MekxQOWF2RUV6ZjFN
            N015aldXTEhmTC9NVWtrdUd4Vm9uNFEKLS0tIGpkQzdOcXRLeXhya05WQ0Z4SEFM
            ZlZ3dTVuYjYxWDAyVEJ3TFVhKzlhRVEKXM9/W9ymJ8PlqJUPX6eILZD9c1D26Iz6
            SPPMV3bqJRw6XgXZi04aJPZ1UkfKrJRzwuih3496rJ2mrEXaYHdIDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-06T08:03:55Z"
    mac: ENC[AES256_GCM,data:hv3AnyBhKmDX4GlDRn5sWTOA3qZ/B/gmMhfp48uPicM/I80uN+jDloNouPOFlfXXsQo17tSzBa/MYF9g4wdboAztSeYvIC3BQyIz/KE5JlmRONY4xIaR69XOqcSMZBWYcVvhVUnkvqtHBj4h2vJ4CxqkOy0RaYJ9xHtjVX4Tklw=,iv:riAGj/D7gkroY/osMxsZfiqHtHKUIDNoe7zDjD0HCG4=,tag:sYeaC7B+NL5omdjFD7Mszg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
