apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-api
  namespace: simplebookmarks
spec:
  commonName: api.${SECRET_SIMPLEBOOKMARKS_DOMAIN}
  secretName: tls-api
  dnsNames:
    - api.${SECRET_SIMPLEBOOKMARKS_DOMAIN}
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
