---
- name: Set hostname to inventory hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  when:
    - ansible_hostname != inventory_hostname

- name: Update /etc/hosts to include hostname
  ansible.builtin.blockinfile:
    path: /etc/hosts
    create: true
    block: |
      127.0.0.1 localhost
      127.0.1.1 {{ inventory_hostname }}

      # The following lines are desirable for IPv6 capable hosts
      ::1 ip6-localhost ip6-loopback
      fe00::0 ip6-localnet
      ff00::0 ip6-mcastprefix
      ff02::1 ip6-allnodes
      ff02::2 ip6-allrouters
      ff02::3 ip6-allhosts

- name: Set system controls for Kubernetes
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/99-kubernetes.conf
    reload: true
  with_dict: "{{ sysctl_config }}"
  vars:
    sysctl_config:
      net.ipv4.ip_forward: 1
      net.ipv4.conf.all.forwarding: 1
      net.ipv6.conf.all.forwarding: 1
      net.bridge.bridge-nf-call-iptables: 1
      net.bridge.bridge-nf-call-ip6tables: 1
      net.ipv4.conf.default.rp_filter: 0
      net.ipv4.conf.all.rp_filter: 0

- name: UFW - Allow incoming
  community.general.ufw:
    direction: incoming
    default: allow

- name: UFW - Allow outgoing
  community.general.ufw:
    direction: outgoing
    default: allow

- name: UFW - Limit SSH
  community.general.ufw:
    rule: limit
    port: ssh
    proto: tcp

#- name: UFW - Allow k3s
#  community.general.ufw:
#    rule: allow
#    port: 6443
#    proto: tcp

#- name: Allow all access from RFC1918 networks to this host
#  community.general.ufw:
#    rule: allow
#    src: '{{ item }}'
#  loop:
#    - 10.0.0.0/8
#    - 172.16.0.0/12
#    - 192.168.0.0/16

- name: UFW - Deny portmapper
  community.general.ufw:
    rule: deny
    port: '111'
    proto: any

- name: Enable UFW
  community.general.ufw:
    state: enabled
