configMapGenerator:
- name: elasticsearch-configuration-cm
  # This configMap contains the necessary templates to configure elasticsearch.
  # The configMap is mounted in the elasticsearch pod.
  # The postExec hook in the helm values calls the run.sh script.
  files:
  - ilm-backup-logs.json
  - mapping-backup-logs.json
  - settings-backup-logs.json
  - template-backup-logs.json
  - run.sh
generatorOptions:
  # If enabled, a hash is added as suffix of the cm name.
  # But the name of the configMap that we use in the HelmRelease values is not updated,
  # so it fails to find the configMap.
  # Disabling it makes the reconciliation in case of the configMap changes a bit longer.
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
