# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:TE/whu7uMlTfLXLmbVZWN28x3/Y/2tNzBDq0c9NUeU3kQXCxUg==,iv:fLBStOZVU7sOgiXJfkSsHyymlmyiwT8YmTvFEMEwI1o=,tag:THK6aW5+pDoM5WpN/RNgSQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1adgzd3kcelpz23rfek7hgp9saega7vea9n2fpkd6qqunpczfpv5sw8ns4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKaEluTWIxaFJ0ZHJQM0Ey
            MzJGYlBxTUIzZmF1Yjh6Y3RMZVBRNklBR0JZCnJOdkdGMWtZK0dZYTZMejd5NnV0
            bmFFVlMwVFlsdGhyckpQOVJxZnhZRUUKLS0tIC9QdGVvSXowZTlBemZwWW9Wa0ND
            UTZ6dk83VVFoSEg5cExWOWdmUXBKdDgKyt/04UYZSx4ZArtd3xQZ8uLRMENRLIV+
            uauuHdoJjI37pXzyRG5CXGesOo4alKEzaApZU6nunf/eD/BtjDxyWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-31T20:53:00Z"
    mac: ENC[AES256_GCM,data:622Lum3V3dah5MsEzPdLuKOEPUXQZLDr/LDrktSq0OTcyzPqfhclYJPsVq9Cgd+P+xIdRM6mB6hxllSlySvmQQIxetP9hzEa7o/RCTlIHMZtpLPlFjGbM+uyUq7zwDUDOQtCaEe0EFiuK1vNB9yXW0qFZUADEIDVEuKU/RBaj7I=,iv:p228ZdVK0jct4qC6tFh76TkmLWJsW5AJo5IDaGDJgeM=,tag:Fx/Hcwnq0Jd4u7FoJ/BQFA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
