apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: alertmanager-discord
    app.kubernetes.io/name: alertmanager-discord
    app.kubernetes.io/part-of: alertmanager
  name: alertmanager-discord
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: alertmanager-discord
  template:
    metadata:
      labels:
        app.kubernetes.io/name: alertmanager-discord
    spec:
      containers:
        image: harbor.dhosting.xyz/horsducommun/alertmanager-discord
        imagePullPolicy: Always
        name: alertmanager-discord
        ports:
        - containerPort: 9094
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        env:
          - name: DISCORD_WEBHOOK
            value: ${SECRET_ALERT_MANAGER_DISCORD_WEBHOOK}
      imagePullSecrets:
      - name: docker-registry-alertmanager-discord
