---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: alertmanager-discord
    app.kubernetes.io/name: alertmanager-discord
    app.kubernetes.io/part-of: alertmanager
  name: alertmanager-discord
spec:
  ports:
  - name: http
    port: 9094
    protocol: TCP
  selector:
    app.kubernetes.io/name: alertmanager-discord
