version: '3'
services:

  postgres:
    image: postgres:11.10-alpine
    container_name: ttrss-postgres
    ports:
      - "5454:5432"
    volumes:
      - ./dbdata:/var/lib/postgresql/data:z
    environment:
      POSTGRES_USER: ttrss
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ttrss

  ttrss:
    build: .
    container_name: ttrss
    environment:
      DB_TYPE: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ttrss
      DB_PASS: admin
      DB_NAME: ttrss
      BASE_URL: http://127.0.0.1:8080
    ports:
      - 8080:8080

  service.mercury: # set Mercury Parser API endpoint to `service.mercury:3000` on TTRSS plugin setting page
    image: wangqiru/mercury-parser-api:latest
    container_name: mercury
    restart: always

volumes:
  db-data:

